name: Run CI Workflow
on:
  push:
    paths:
      - "**.py"
      - "**requirements*.txt"

jobs:
  run-ci-static-analysis:
    runs-on: ubuntu-latest
    env:
      python-version: 3.10.3
      architecture: x64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }} ${{ env.architecture }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
          architecture: ${{ env.architecture }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run black formatter check
        run: black --check --diff --color ./src 
      - name: Run flake8 linter
        run: flake8 ./src --count --statistics
      - name: Run mypy static type checking
        run: mypy ./src
      - name: Run isort import order check
        run: isort ./src --check-only
  run-ci-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        architecture:
          - x64
          - x86
        python-version:
          - 3.10.3
        exclude:
          # As-of 2022-03-21, there is no canned Python installation available for linux/mac x86
          - os: ubuntu-latest
            architecture: x86
          - os: macOS-latest
            architecture: x86
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Build package wheels
        run: python -m build --wheel
      - name: Install package wheels
        run: pip install dist/*.whl
        shell: bash
      - name: Run unit tests with pytest
        run: |
          pytest ./tests -v
